name: CI for Perl-Nexmo-SMS
on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
jobs:
  build:
    runs-on: "windows-latest"
    strategy:
      fail-fast: false
      matrix:
        perl: ["5.38"]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: strawberry
      - run: perl -V
      - name: Setup Alien::MSYS directory
        run: |
          git clone https://github.com/hakonhagland/Alien-MSYS.git
          cd Alien-MSYS
          git fetch origin debug:debug
          git checkout debug
      - name: Install dependencies
        run: |
          cd Alien-MSYS
          cpanm --notest Dist::Zilla
          dzil authordeps --missing | cpanm --notest
          dzil listdeps --missing | cpanm --notest
          dzil build
      - name: Add Strawberry Perl to PATH
        shell: pwsh
        run: |
          $perlPaths = &where.exe perl
          echo "All Perl paths found:"
          echo $perlPaths
          $perlPath = $perlPaths | Select-String -Pattern "C:\\hostedtoolcache\\windows\\strawberry-perl"
          if ($perlPath) {
            $perlDir = [System.IO.Path]::GetDirectoryName(($perlPath | Select-Object -First 1).Line)
            echo "Strawberry Perl found at $perlDir"
            echo "STRAWBERRY_PERL_PATH=$perlDir" >> $env:GITHUB_ENV
          } else {
            echo "Strawberry Perl not found"
          }
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel mingw-w64-x86_64-toolchain m4
      - name: Add MSYS2 to Path
        run: |
          echo "C:\msys64\usr\bin" >> $env:GITHUB_PATH
          ls C:\msys64\usr\bin
      - name: Install Alien::MSYS
        run: |
          $env:PATH = "$env:STRAWBERRY_PERL_PATH;$env:PATH"
          cd Alien-MSYS\Alien-MSYS-0.17
          $env:PERL_ALIEN_MSYS_BIN = "C:\msys64\usr\bin"
          perl Makefile.PL
          gmake
          echo "XYZ"
