name: CI for Perl-Nexmo-SMS
on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
jobs:
  build:
    runs-on: "windows-latest"
    strategy:
      fail-fast: false
      matrix:
        perl: ["5.38"]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel mingw-w64-x86_64-toolchain
      - name: Update MSYS2 and install m4 package
        # Note: adding m4 to the install list in the setup-msys2 action did not work
        #  so we have to install it manually
        run: |
          C:\msys64\usr\bin\pacman -Syu --noconfirm
          C:\msys64\usr\bin\pacman -S --noconfirm m4
        shell: cmd
      - name: Add MSYS2 to PATH
        run: |
          echo "C:\msys64\usr\bin" >> $env:GITHUB_PATH
      - name: Download gsl
        run: |
          wget https://ftp.gnu.org/gnu/gsl/gsl-2.8.tar.gz
          tar -xzf gsl-2.8.tar.gz
          ls .
