name: CI for Perl-Nexmo-SMS
on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
jobs:
  build:
    runs-on: "windows-latest"
    strategy:
      fail-fast: false
      matrix:
        perl: ["5.38"]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: strawberry
      - run: perl -V
      - name: Setup Alien::MSYS directory
        run: |
          git clone https://github.com/hakonhagland/Alien-MSYS.git
          cd Alien-MSYS
          git fetch origin debug:debug
          git checkout debug
      - name: Install dependencies
        run: |
          cd Alien-MSYS
          cpanm --notest Dist::Zilla
          dzil authordeps --missing | cpanm --notest
          dzil listdeps --missing | cpanm --notest
          dzil build
      - name: Install Alien::MSYS
        run: |
          Write-Output $PWD
          Get-ChildItem Alien-MSYS
#          cd Alien-MSYS\Alien-MSYS-0.017
#          perl Makefile.PL
#          gmake
